apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeatconf
data:
  filebeat.yml: |-
    filebeat.inputs:
    - input_type: log
      paths:
        - /data/log/*/*.log
      tail_files: true
      # 这里 fileds 添加上面 filebeat 容器中注入的 downwardAPI 相关信息
      fields:
        pod_name: '${podName}'
        pod_ip: '${podIp}'
        pod_namespace: '${podNamespace}'
    output.kafka:
      # hosts: ["kafka:9092"]
      hosts: ["kafka.logging.svc.cluster.local:9092"]
      # 这里 topic 需要和前面部署的 Logstash 中配置的一致
      topic: "filebeat-sidecar"
      codec.json:
        pretty: false
      keep_alive: 30s
