apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
  namespace: default
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: demo
      image: vvoo/demoapp:v1.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "100m"
          memory: 100Mi
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: prestop-vl
          mountPath: /data
      lifecycle:
        postStart:
          exec:
            command:
              [
                "/bin/sh",
                "-c",
                "iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-ports 80",
              ]
        preStop:
          exec:
            command:
              [
                "/bin/sh",
                "-c",
                'echo "$(date) start stop" >> /data/test.log && sleep 60 && echo "$(date) end stop" >> /data/test.log',
              ]
  restartPolicy: Always
  volumes:
    - name: prestop-vl
      persistentVolumeClaim:
        claimName: test-prestop-pvc
