version: "3.3"

services:
  envoy:
    image: envoyproxy/envoy:v1.32.5
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - demoapp_service1
      - demoapp_service2
    ports:
      - "${PORT_PROXY:-50051}:50051"
      - "${PORT_ADMIN:-9901}:9901"
    networks:
      envoymesh:
        ipv4_address: 172.16.3.2
        aliases:
          - forward-proxy
  
  demoapp_service1:
    image: vvoo/demoapp-grpc:v1.2
    ports:
      - "${PORT:-50052}:50051"
    networks:
      envoymesh:
        ipv4_address: 172.16.3.3
        aliases:
          - service1
  
  demoapp_service2:
    image: vvoo/demoapp-grpc:v1.2
    ports:
      - "${PORT:-50053}:50051"
    networks:
      envoymesh:
        ipv4_address: 172.16.3.4
        aliases:
          - service2
  
  statsd_exporter:
    image: prom/statsd-exporter:v0.28.0
    ports:
      - 9102:9102
      - 9125:9125
    networks:
      envoymesh:
        ipv4_address: 172.16.3.5
        aliases:
          - statsd_exporter

networks:
  envoymesh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.3.0/24