apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
    version: v2.1
  name: demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
        version: v2.1
    spec:
      containers:
      - image: vvoo/demoapp:v2.1
        imagePullPolicy: IfNotPresent
        name: demoapp
        env:
        - name: "PORT"
          value: "8080"
        - name: "VERSION"
          value: "v2.1"
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
