apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-vm
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
    remote_write: 
    - url: http://victoria-metrics:8428/api/v1/write
    scrape_configs:
      - job_name: 'nodes'
        scrape_interval: 5s
        static_configs:
          - targets: ['10.200.13.6:9100','10.200.13.9:9100','10.200.13.10:9100','10.200.13.11:9100','10.200.13.16:9100']
        relabel_configs: 
        - source_labels: [__address__]
          regex: "(.*):(.*)"
          replacement: "${1}"
          target_label: 'ip'
          action: replace  
