apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      ctlr: redis
  template:
    metadata:
      labels:    # Pod的标签，将被demoapp Pod选择作为参照系
        app: redis
        ctlr: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-required
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demoapp
      ctlr: pod-affinity-required
  template:
    metadata:
      labels:
        app: demoapp
        ctlr: pod-affinity-required
    spec:
      containers:
      - name: demoapp
        image: vvoo/demoapp:v1.0
      affinity:
        podAffinity:                # Pod亲和调度
          requiredDuringSchedulingIgnoredDuringExecution:   # 强制亲和定义
          - labelSelector:          # Pod对象标签选择器，用于确定放置当前Pod的参照系
              matchExpressions:
              - key: app
                operator: In
                values: ["redis"]
              - key: ctlr
                operator: In
                values: ["redis"]
            topologyKey: zone       # 拓扑建，用于确定节点位置拓扑的节点标签，必须。